apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: devops
  namespace: devops
spec:
  hosts:
    - devops.default.svc.cluster.local
  http:
    - match:
        - uri:
            prefix: "/v1"
      route:
        - destination:
            host: devops.default.svc.cluster.local
            subnet: v1
    - route:
        - destination:
            host: devops.default.svc.cluster.local
            subnet: v2