version: '3.3'

networks:
    devops:
      name: devops

services:
    webb_app:
        container_name: web_app
        image: maiaitha/web_app:latest
        ports:
            - "3000:3000"
        depends_on:
            - redis
        environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        networks:
            - devops


    redis:
        container_name: redis
        image: redis
        ports:
            - "6379:6379"
        networks:
            - devops