version: '2'

networks:
    devops_test:
      name: devops_test

services:
    devops_webserv:
        container_name: devops_webserv
        image: maiaitha/devops_webserv:latest
        ports:
            - "3000:3000"
        networks:
            - devops_test

    