version: '2'

networks:
    devops_test:
      name: devops_test

devops_client:
        container_name: devops_client
        image: maiaitha/devops_client:latest
        ports:
            - "3001:3001"
        networks:
            - devops_test