---
- name: Install npm, Node.js, and Redis
  hosts: all
  become: true
  tasks:
    - name: Install npm
      package:
        name: npm
        state: present

    - name: Install Node.js
      package:
        name: nodejs
        state: present

    - name: Install Redis
      package:
        name: redis
        state: present