---
- hosts: all
  tasks:

    - name: Install Python
      become: yes
      apt:
        name: python3
        state: present

    - name: Install pip
      become: yes
      apt:
        name: python3-pip
        state: present

    - name: Install Redis
      become: yes
      apt:
        name: redis-server
        state: present

    - name: Install Flask
      become: yes
      pip:
        name: Flask
        state: present

    - name: Install Uuid
      become: yes
      pip:
        name: uuid
        state: present
